# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_student_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='prefered_branch',
            new_name='preferred_branch',
        ),
        migrations.AddField(
            model_name='faculty',
            name='joined_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
