# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='name',
            field=models.CharField(default='XYZ', max_length=100),
            preserve_default=False,
        ),
    ]
