# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20170116_0320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testattempt',
            old_name='markes_obtained',
            new_name='marks_obtained',
        ),
        migrations.AddField(
            model_name='testattempt',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
    ]
