# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 05:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20170118_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_in_board_exam', models.IntegerField()),
                ('marks_in_institute_exam', models.IntegerField()),
                ('monthly_family_income', models.IntegerField()),
                ('other_scholarship', models.BooleanField()),
                ('applied_on', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Student')),
            ],
        ),
    ]
