# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20170202_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.AddField(
            model_name='faculty',
            name='teaches',
            field=models.ManyToManyField(to='home.Subject'),
        ),
    ]
